name: Validate licenses
on: [push, pull_request]
jobs:
  validate:
    name: Licensed CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: jonabc/licensed-ci@v1.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
